#!/bin/sh
set -eu

: "${PILOT_FRONTEND_PUBLIC_URL:=}"
: "${VITE_API_BASE_URL:=/api}"
: "${VITE_AUTH_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_CANDIDATE_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_CATALOG_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_DOCUMENT_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_FINANCE_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_MEBBIS_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_PLATFORM_API_BASE_URL:=$VITE_API_BASE_URL}"
: "${VITE_TRAINING_API_BASE_URL:=$VITE_API_BASE_URL}"

envsubst '${PILOT_FRONTEND_PUBLIC_URL} ${VITE_API_BASE_URL} ${VITE_AUTH_API_BASE_URL} ${VITE_CANDIDATE_API_BASE_URL} ${VITE_CATALOG_API_BASE_URL} ${VITE_DOCUMENT_API_BASE_URL} ${VITE_FINANCE_API_BASE_URL} ${VITE_MEBBIS_API_BASE_URL} ${VITE_PLATFORM_API_BASE_URL} ${VITE_TRAINING_API_BASE_URL}' \
  < /usr/share/nginx/html/env-config.template.json \
  > /usr/share/nginx/html/env-config.json
